// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BlackIceSoftware.CBExtensionPkg
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCBExtensionPkgPkgString = "b467e5f1-4a69-4ad8-a2a6-0d8bf3932e0e";
        public const string guidCBExtensionPkgCmdSetString = "3001e580-502a-454e-9ff4-9f70884be3d8";
        public const string guidImagesString = "981fd8e3-1132-4395-84be-c512a4801b53";
        public static Guid guidCBExtensionPkgPkg = new Guid(guidCBExtensionPkgPkgString);
        public static Guid guidCBExtensionPkgCmdSet = new Guid(guidCBExtensionPkgCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CBAutoSaveGroup = 0x1020;
        public const int cmdIdCBAutoSave = 0x0100;
        public const int cmdIdCBAutoSaveProject = 0x0101;
        public const int bmpPic1 = 0x0001;
    }
}
