// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BlackIceSoftware.CBExtensionPkg
{
    static class Vsix
    {
        public const string Id = "b467e5f1-4a69-4ad8-a2a6-0d8bf3932e0e";
        public const string Name = "CBAutoSave";
        public const string Description = @"Save modified documents, projects, and solution when Visual Studio loses focus.";
        public const string Language = "en-US";
        public const string Version = "1.11.3";
        public const string Author = "BlackIce Software";
        public const string Tags = "";
    }
}
